### ISSUE TITLE
bug: typing "v" in comments toggles compressor

### ISSUE THREAD

**Issue by adolson** [dan-online/youtubeaudiocompressor#160]
### Description of the bug

The V hotkey toggles the compressor on and off, but this is a bit jolting when commenting on the video. It shouldn't be listening when typing in the comment field.

I would simply disable the hotkey entirely but I don't see any option to do so (I may be just missing it?).

### Steps To Reproduce

Go to video
Play video
Type comments including the letter V

### Additional Information

I am using Firefox on Debian Linux.

**Comment by dan-online** [comment]
Hey @adolson, this had been fixed in v 1.0.4 which I just pushed to the store. Hopefully it will be out in about a day, let me know if you have any more issues!
