### ISSUE TITLE
bug: fails to load when navigating in-page

### ISSUE THREAD

**Issue by jeremyjohn** [dan-online/youtubeaudiocompressor#24]
Sometimes the plugin does not load and show the icon.

Usually happens when you click a video from youtube home page or a playlist.
If you open the video link directly it loads fine but if it's loading by page stage change it will not show the icon.

Maybe add some delay or page state/play state change detection?

**Comment by dan-online** [comment]
Hey @jeremyjohn, I'll take a look at this, I was able to repro so I should be able to fix it

**Comment by dan-online** [comment]
I have pushed a fix for this as version 1.0.1

Solution: The plugin checks every second to make sure the button is on the page. This won't affect page performance and I added a clean-up function to guarantee it. This change should be published within a day and your device should auto-update the extension. However you can also force update your extensions at ``chrome://extensions``

I hope this fixes the issue!
