### ISSUE TITLE
bug: 360° VR video player fails to load.

### ISSUE THREAD

**Issue by jeremyjohn** [dan-online/youtubeaudiocompressor#52]
If the compressor is enabled and you open a 360° VR video, the YT VR player fails to load. Instead the normal YT player will load and the video will be messed up.

If the compressor is disabled and open a 360° VR video it works fine. You can then enable the compressor without any issues.

**Comment by dan-online** [comment]
Interesting, could you provide an example video? I don't seem to be able to reproduce this.
